### ISSUE TITLE
Conversion of IMU changes (x,y,z) angular velocity and linear acceleration to (z, -x, y)

### ISSUE THREAD

**Issue by maxime-clem** [RobotecAI/ROS2ForUnitySVLBridge#2]
Is there a reason for changing from `(x,y,z)` to `(z,-x,y)` ? If this is a mistake I am happy to create a PR to fix it.
https://github.com/RobotecAI/ROS2ForUnitySVLBridge/blob/6cb1bb5864b6061951f44863a55426f691066174/ROS2ForUnitySVLBridgeConversions.cs#L338-L339

Thank you for your help.

**Comment by adamdbrw** [comment]
First look: these are Unity to ROS coordinates transformations. Are you getting incorrect data?

**Comment by maxime-clem** [comment]
Is it possible that SVL is already doing the transformation from Unity to ROS coordinates ?
In the attached video I show the value of the IMU sensor in SVL and in terminal I show the output of command `ros2 topic echo /imu/imu_raw | grep angular_velocity: -A 3`. You can see the angular velocity value looks correct in SVL (negative `z` value when turning right, positive `z` value when turning left).

https://user-images.githubusercontent.com/78338830/144392353-16ef8b00-c5db-436b-947b-51b2ed06817e.mp4

**Comment by wep21** [comment]
I guess coordinates conversion is executed  [here](https://github.com/lgsvl/ImuSensor/blob/7a0bed6c15917fd93b3494859d7cda040c385f8e/ImuSensor.cs#L176) in svl simulator.

**Comment by pijaro** [comment]
Thanks for pointing the issue, I will look into this.

**Comment by pijaro** [comment]
Thank you @maxime-clem and @wep21. It was most probably a leftover from older (pre 2021.x) versions of simulator. I fixed it by removing the unnecessary conversion.

I've uploaded an updated bridge as well, it should be fetched the next time you use SVL. Will also wait a bit before resolving this issue, just to give some time to verify that everything is in order now.
